# Generated by Django 5.1.7 on 2025-04-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClass2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('napis', models.CharField(max_length=200)),
                ('liczba', models.IntegerField()),
            ],
        ),
    ]
