# Generated by Django 5.1.7 on 2025-05-11 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badanie_title', models.CharField(max_length=50)),
                ('result_type', models.CharField(choices=[('HR', 'Heart Rate'), ('BP', 'Blood Pressure'), ('ECG', 'EKG'), ('GLU', 'Glukoza'), ('INNE', 'Inne')], max_length=10)),
                ('badanie_data', models.DateTimeField(auto_now_add=True)),
                ('badanie_value', models.CharField(blank=True, max_length=100, null=True)),
                ('badanie_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('badanie_notatki', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wizyty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizyta_data', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='wizyty_photos/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
