# Generated by Django 4.2.21 on 2025-05-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_badania_wizyty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badania',
            name='badanie_data',
            field=models.DateTimeField(),
        ),
    ]
