# Generated by Django 4.2.21 on 2025-05-15 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_badania_badanie_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pesel',
            field=models.CharField(default=123, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{3}$', message='Wprowadź poprawny numer PESEL (3-cyfrowy).')]),
            preserve_default=False,
        ),
    ]
