# Generated by Django 4.2.21 on 2025-05-15 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_pesel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pesel',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', message='Wprowadź poprawny numer PESEL (3-cyfrowy).')]),
        ),
    ]
