# Generated by Django 4.2.21 on 2025-05-31 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_customuser_pesel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pesel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='Wprowadź poprawny numer PESEL (11-cyfrowy).')]),
        ),
    ]
